CREATE DATABASE IF NOT EXISTS guestbook;
CREATE USER 'root'@'${MYSQL_HOST}' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON guestbook.* TO 'root'@'${MYSQL_HOST}';

USE guestbook;

CREATE TABLE IF NOT EXISTS guestbook.entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    message TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
