---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webapps
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_HOST : ZGI=
  MYSQL_USER : cm9vdA==
  MYSQL_PASSWORD : cm9vdEAxMjM=
  MYSQL_NAME : Z3Vlc3Rib29r 
  MYSQL_ROOT_PASSWORD: cm9vdEAxMjM= 

