---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: webapps
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  password: cm9vdEAxMjM=
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sql-script
data:
  inti.sql: |
    CREATE DATABASE IF NOT EXISTS guestbook;
    USE guestbook;
    CREATE TABLE IF NOT EXISTS guestbook.entries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        message TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
