---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: webapps
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: reactjs
          image: 17rj/frontend-reactjs-3tier:latest
          ports:
            - containerPort: 3000
