---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: webapps
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
